### ISSUE TITLE
mmtf/tests/testdatastore missing from PyPI 1.0.5 tarball

### ISSUE THREAD

**Issue by rathann** [rcsb/mmtf-python#22]
`mmtf/tests/testdatastore` is missing from the 1.0.5 tarball available from PyPI, so some tests are failing:
```
[mockbuild@f1c696a972e3481593111ec80af39a2a mmtf-python-1.0.5]$ python2 setup.py nosetests --processes=4
['mmtf', 'mmtf.codecs', 'mmtf.utils', 'mmtf.api', 'mmtf.converters', 'mmtf.tests', 'mmtf.codecs.encoders', 'mmtf.codecs.decoders']
running nosetests
running egg_info
writing requirements to mmtf_python.egg-info/requires.txt
writing mmtf_python.egg-info/PKG-INFO
writing top-level names to mmtf_python.egg-info/top_level.txt
writing dependency_links to mmtf_python.egg-info/dependency_links.txt
writing entry points to mmtf_python.egg-info/entry_points.txt
reading manifest file 'mmtf_python.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mmtf_python.egg-info/SOURCES.txt'
.....................E.EE...EE
======================================================================
ERROR: test_decoder (mmtf.tests.codec_tests.ConverterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/tests/codec_tests.py", line 180, in test_decoder
    decoded = parse("mmtf/tests/testdatastore/4CUP.mmtf")
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/api/default_api.py", line 78, in parse
    newDecoder.decode_data(msgpack.unpackb(open(file_path, "rb").read()))
IOError: [Errno 2] No such file or directory: 'mmtf/tests/testdatastore/4CUP.mmtf'

======================================================================
ERROR: test_gz_decoder (mmtf.tests.codec_tests.ConverterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/tests/codec_tests.py", line 183, in test_gz_decoder
    decoded = parse_gzip("mmtf/tests/testdatastore/4CUP.mmtf.gz")
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/api/default_api.py", line 87, in parse_gzip
    newDecoder.decode_data(msgpack.unpackb(gzip.open(file_path, "rb").read()))
  File "/usr/lib64/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'mmtf/tests/testdatastore/4CUP.mmtf.gz'

======================================================================
ERROR: test_gzip_open (mmtf.tests.codec_tests.ConverterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/tests/codec_tests.py", line 191, in test_gzip_open
    ungzip_data(open("mmtf/tests/testdatastore/4CUP.mmtf.gz","rb").read())
IOError: [Errno 2] No such file or directory: 'mmtf/tests/testdatastore/4CUP.mmtf.gz'

======================================================================
ERROR: test_round_trip (mmtf.tests.codec_tests.ConverterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/tests/codec_tests.py", line 294, in test_round_trip
    data_in = parse_gzip("mmtf/tests/testdatastore/4CUP.mmtf.gz")
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/api/default_api.py", line 87, in parse_gzip
    newDecoder.decode_data(msgpack.unpackb(gzip.open(file_path, "rb").read()))
  File "/usr/lib64/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'mmtf/tests/testdatastore/4CUP.mmtf.gz'

======================================================================
ERROR: test_round_trip_list (mmtf.tests.codec_tests.ConverterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
    test(orig)
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib64/python2.7/unittest/case.py", line 431, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/tests/codec_tests.py", line 355, in test_round_trip_list
    self.round_trip(pdb_id)
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/tests/codec_tests.py", line 300, in round_trip
    data_in = fetch(pdb_id)
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/api/default_api.py", line 69, in fetch
    decoder.decode_data(get_raw_data_from_url(pdb_id))
  File "/builddir/build/BUILD/mmtf-python-1.0.5/mmtf/api/default_api.py", line 44, in get_raw_data_from_url
    response = urllib2.urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1230, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1203, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
    raise TimedOutException()
TimedOutException: 'test_round_trip_list (mmtf.tests.codec_tests.ConverterTests)'

----------------------------------------------------------------------
Ran 30 tests in 10.279s

FAILED (errors=5)
```

**Comment by abradle** [comment]
Closed by https://github.com/rcsb/mmtf-python/pull/25

Thanks for finding this!
